dist: xenial

language: go
go:
- 1.13.1

git:
  submodules: true

env:
  global:
    - HUGO_VERSION=0.62.2
    - HUGO_ARCH=Linux-64bit

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_${HUGO_ARCH}.deb
  - sudo dpkg -i hugo_${HUGO_VERSION}_${HUGO_ARCH}.deb

script:
  - hugo -D

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  repo: confucianh/confucianh.github.io
  target_branch: master
  on:
    branch: master

# notifications:
#   email:
#     recipients:
#       - confucian.huo@protomail.com
#   on_success: change
#   on_failure: always
